project:
  type: website

website:
  title: "mysite"
  navbar:
    background: primary
    search: true
    left:
     - href: about.qmd
       text: start here!
     - href: index.Rmd
       text: data analysis 101
     - href: liveapp/interact.qmd
       text: interactive spotify
    tools:
          - icon: github
            menu:
              - text: Source Code
                url:  https://github.com/ValColorado/spotify-rewrapped
              - text: Give feedback
                url:  https://github.com/ValColorado/spotify-rewrapped/issues/new

format:
  html:
    theme: quartz
    css: styles.css
    toc: true



